#!/bin/bash
tmpfile="/$USER/.folder_check.tmp"

diskfree="$( df -h | grep "/var/tsbackup" | awk '{print "Used: " $3 " Free: " $4}')"
echo "Usage Stats for /var/tsbackup on Tsbackup:" >>$tmpfile
echo $diskfree >>$tmpfile
echo >>$tmpfile
echo "The following directories are older than 45 days and can be deleted:" >>$tmpfile
for dir in $(/home/paulm/bin/outdated); do
#	echo /var/tsbackup/$dir >>$tmpfile
	du -sh /var/tsbackup/$dir  >> $tmpfile
done
mailx -n -r paulm@freegeek.org -s "Folders that can be deleted on tsbackup"  support-staff@lists.freegeek.org < $tmpfile
rm $tmpfile

