#!/bin/bash
help(){
cat <<EOF
Usage : $0 [OPTION]
Lists folders due for deletion (and sends email)
	-m 		Send email rather than printing to stdout.
        -p [PATH]       Use this option to specify the path of the backup dir
	-r [EMAIL]	Specify optional adress to send email to. 
			It is not necessary to specify an address. 
			There is one set by default in the script.
			Requires the -m option.
	-f [EMAIL]	Set the from email adress. It is not necessary to 
			specify an address. There is one set by default in
			the script. Requires the -m option.
	-h 		print this message

This script prints info about backup folders on tsbackup that are due for deletion. It is primarily intended for use with cron. 
EOF

if [[ -n $1 && $(echo {0..255}) =~ $1 ]]; then
        exit $1
else
        exit 0
fi
}


# process option arguments
while getopts "hmr:f:p:" option; do
        case "$option" in
                h) help;;
                m) mail=true;;
		r) recipient=$OPTARG;;
		f) sender=$OPTARG;;
                p) backup_path=$OPTARG;;
                \?)  echo "bad option supplied" 
                       help 2
		;;
        esac
done
if [[ $recipient && ! $mail ]]; then
	echo "The -r option requires the use of -m"
elif [[ $sender && ! $mail ]]; then
        echo "The -f option requires the use of -m"
fi 


# default variables
if [[ $mail ]]; then
	if [[ -z $recipient ]]; then
		recipient="support-staff@lists.freegeek.org"
	fi
	if [[ -z $sender ]]; then
                sender="paulm@freegeek.org "
        fi
fi

#backup_host="tsbackup"
backup_host=$HOSTNAME
default_backup_path="/var/tsbackup"
path=/home/paulm/bin/    # note trailing slash

if [[ -z $backup_path ]]; then
    backup_path=$default_backup_path
fi

if [[ ! -e $backup_path ]]; then
    echo "$backup_path does not exist!"
    exit 3
fi

tmpfile="$HOME/.folder_check.tmp"

diskfree="$( df -h | grep "$backup_path" | awk '{print "Used: " $3 " Free: " $4}')"
echo "Usage Stats for $backup_path on $backup_host:" >>$tmpfile
echo $diskfree >>$tmpfile
echo >>$tmpfile

# collect unresolved ticket details
declare -A unresolved

echo "The following directories are older than 45 days and can be deleted:" >>$tmpfile
for dir in $(${path}outdated $backup_path); do
    ticket=$(echo $dir | awk -F - '{print $2}')
    while read line; do
        if [[ $line =~  "Subject:" ]]; then 
            subject=$(echo -n $line | awk '{$1=""; print $0}')
        elif [[ $line =~ "Status:" ]]; then
            status=$(echo -n $line | awk '{$1=""; print $0}')
        fi
    done < <(wget --keep-session-cookies  --save-cookies cookies.txt  --post-data 'user=tsrobot&pass=EucNabs4' -qO-  todo.freegeek.org/REST/1.0/ticket/${ticket}/show/)
    size=$(du -sh ${backup_path}/${dir} | awk '{print $1}')
    if [[ $status =~ "resolved" ]]; then
        printf "/var/tsbackup/%s\t%s\t%s\t%s\n" "$dir" "$size" "$status" "$subject" >>$tmpfile
    else
        
        # push ticket on to list of unresolved tickets
        unresolved_ticket_list=(${unresolved_ticket_list[@]}  "$ticket")
        # store details in associative array (fake multi_dimensional)
        for value in dir size status subject; do
            unresolved[${ticket}_$value]=${!value}
        done
    fi
done

echo 

# we have tickets that have a status that is not resolved
if (( ${#unresolved_ticket_list[@]} > 0 )); then
    echo  >>$tmpfile
    echo "The following tickets are older than 45 days but are not marked as resolved," >>$tmpfile
    echo "you should manually inspect the ticket before proceeding." >>$tmpfile
    #loop over list of unresolved tickets
    for unresolved_ticket in ${unresolved_ticket_list[@]}; do
        # referencing our fake multi-D array
        printf "/var/tsbackup/%s\t%s\t%s\t%s\n" "${unresolved[${unresolved_ticket}_dir]}" "${unresolved[${unresolved_ticket}_size]}" "${unresolved[${unresolved_ticket}_status]}" "${unresolved[${unresolved_ticket}_subject]}" >>$tmpfile
    done
fi

echo

# if its the beginning of the year check for wrong dates
if (( $(date +%m) < 3 )); then 
    echo "The following directories  appear to be  older than 300 days" >> $tmpfile 
    echo "It appears someone may not know what year it is." >>$tmpfile
    for dir in $(${path}newyearcheck $backup_path); do
        ticket=$(echo $dir | awk -F - '{print $2}')
        while read line; do
            if [[ $line =~  "Subject:" ]]; then 
                subject=$(echo -n $line | awk '{$1=""; print $0}')
            elif [[ $line =~ "Status:" ]]; then
                status=$(echo -n $line | awk '{$1=""; print $0}')
            fi
        done < <(wget --keep-session-cookies  --save-cookies cookies.txt  --post-data 'user=tsrobot&pass=EucNabs4' -qO-  todo.freegeek.org/REST/1.0/ticket/${ticket}/show/)
        size=$(du -sh ${backup_path}/${dir} | awk '{print $1}')
            printf "/var/tsbackup/%s\t%s\t%s\t%s\n" "$dir" "$size" "$status" "$subject" >>$tmpfile
    done     
fi

if [[ $mail ]]; then
	 mailx -n -r $sender -s "Folders that can be deleted on $backup_host" $recipient < $tmpfile
	
	# echo "mailx -n -r $sender -s Folders that can be deleted on $backup_host $recipient < $tmpfile"
else
	cat $tmpfile
fi
rm $tmpfile
