#!/bin/bash

monitor_choice=$(zenity --list --radiolist --column ' ' --column 'Monitor Setting' True "Main Monitor Left" \
False "Main Monitor Right" \
False "Second Monitor Off")

echo $monitor_choice
if [[ $monitor_choice =~ "Left" ]]; then
  xrandr --output DVI-0 --auto --left-of VGA-0 --rotate normal
  xrandr --output DVI-0 --auto --left-of VGA-0 --rotate normal
elif [[ $monitor_choice =~ "Right" ]]; then
  xrandr --output DVI-0 --auto --right-of VGA-0 --rotate normal
  xrandr --output DVI-0 --auto --right-of VGA-0 --rotate normal
elif [[ $monitor_choice =~ "Off" ]]; then 
  xrandr --output DVI-0 --off 
  xrandr --output DVI-0 --off
fi

