#!/usr/bin/python

import os
import sys
import StringIO
import datetime
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-l', '--limit', default=45, type=int, help="Cutoff days, defaults to 45")
parser.add_argument('-p', '--path', default='/var/tsbackup',help="path to backup directory, defaults to /var/tsbackup")
args = parser.parse_args()
limit = args.limit
path = args.path

today = datetime.datetime.today()
timedelta = datetime.timedelta(limit)
cutoff = today - timedelta

try:
    file_listing = os.listdir(path)
    for file in file_listing:
        flist = file.split('-')
	mydate = flist[0]
	fdate_string = "%s-%s-%s" % (mydate[0:4],mydate[4:6],mydate[6:8])
	try:
	    fdate = datetime.datetime.strptime( fdate_string , '%Y-%m-%d')
	    if fdate < cutoff:
	        print file
	except:
		pass
except:
    print path, 'is not a valid path'
