#!/usr/bin/python

import os
import sys
import StringIO
import datetime

today = datetime.datetime.today()
timedelta = datetime.timedelta(45)
cutoff = today - timedelta

default_path = "/var/tsbackup"
try:
    sys.argv[1]
    path = sys.argv[1]
except:
    path = default_path


try:
    file_listing = os.listdir(path)
    for file in file_listing:
        flist = file.split('-')
	mydate = flist[0]
	fdate_string = "%s-%s-%s" % (mydate[0:4],mydate[4:6],mydate[6:8])
	try:
	    fdate = datetime.datetime.strptime( fdate_string , '%Y-%m-%d')
	    if fdate < cutoff:
	        print file
	except:
		pass
except:
    print path, 'is not a valid path'
