#!/bin/bash
# this file has the following standard layout
# CONFIGURATION
# help function
# INCLUDES
#FUNCTIONS
# process option arguments
# MAIN

# CONFIGURATION

help(){
cat <<EOF 

usage: $0 [OPTION]...
Check for over and near quota mailboxes

-m          send an email
-r          sets the recipient (defaults technocrats@freegeek.org
-f          changes the from adress from the default
-h			prints this message

This is  script will report on over or near quota mail boxes.
It will also delete mailquotawarn files when users are no longer over quota
EOF

# if $1 exists and is a number 0..255 return that otherwise return 0
if [[ -n $1 && $(echo {0..255}) =~ $1 ]]; then
        exit $1
else
	exit 0
fi
}
# INCLUDES
#FUNCTIONS
# process option arguments
while getopts "hmf:r:" option; do		# w: place variable following w in $OPTARG
	case "$option" in
		h) help;;
        m) mail="true";;
        r) recipient=$OPTARG;;
        f) sender=$OPTARG;;
		[?])  echo "bad option supplied" ; 
			help;;	
	esac
done

# default variables
if [[ $mail ]]; then
        if [[ -z $recipient ]]; then
                recipient="technocrats@freegeek.org"
        fi
        if [[ -z $sender ]]; then
                sender="a.robot@freegeek.org "
        fi
fi

#MAIN
tmpfile="$HOME/.quota_check.tmp"
echo "The following users are near or over their mail quota:" >>$tmpfile
echo >>$tmpfile

bad_users=0

for warning in $(find /var/mail/virtual/freegeek.org/ -name "quota*"); do
    maildirpath=$(dirname $warning)
    mailboxpath=$(echo $maildirpath | sed 's/Maildir//')
    mailuser=$(echo $mailboxpath | awk -F/ '{print $(NF -1)}')
    diskusage=$(du -sb $mailboxpath| awk '{print$1}')
    mailusage=$(du -sb $maildirpath| awk '{print$1}')
    if [[  -e ${maildirpath}/.Spam ]]; then
        spamusage=$(du -sb ${maildirpath}/.Spam | awk '{print$1}')
    else
        spamusage="???"
    fi
    if [[  -e ${maildirpath}/maildirsize ]]; then
        quota=$(head -1 ${maildirpath}/maildirsize | sed 's/S//')
    else
        quota=312428800
    fi
    qpercent=$(echo "$quota * 90 /100" | bc)
    usagepercent=$(echo "$diskusage / $quota * 100" | bc -l | cut -b 1-5)
    mailpercent=$(echo "$mailusage / $quota  * 100" | bc -l | cut -b 1-2)
    if [[ $spamusage != "???" ]] ; then
        spampercent=$(echo "$spamusage / $quota * 100" | bc -l | cut -b 1-4)
    else
        spampercent="???"
    fi
    if [[ $diskusage -lt $qpercent ]];then
        rm $warning
    else
        let bad_users++
        echo "${mailuser} is at ${usagepercent}% of quota, ${mailpercent}% is mail and ${spampercent}% is spam" >>$tmpfile
    fi
done

echo >>$tmpfile

if [[ $mail ]]; then
        echo "your ever humble servant,">>$tmpfile
        echo "                    A. Robot">>$tmpfile
        echo >>$tmpfile
        echo "---" >>$tmpfile
        echo "The city's central computer told you? R2D2, you know better than to trust a strange computer!">>$tmpfile
        if [[ $bad_users -gt 0 ]]; then
            mailx -n  -s "Over quota mailboxes on $HOSTNAME" $recipient < $tmpfile
        fi
else
        cat $tmpfile
fi
rm $tmpfile 
